Traceback (most recent call last):
  File "/home/alphinos-manjaro/Projects/04-python/00-Udemy_Course/02-Traceback.py", line 6, in main
    file = open(file_name)
FileNotFoundError: [Errno 2] No such file or directory: 'file_i.txt'
Traceback (most recent call last):
  File "/home/alphinos-manjaro/Projects/04-python/00-Udemy_Course/02-Traceback.py", line 6, in main
    file = open(file_name)
FileNotFoundError: [Errno 2] No such file or directory: 'xx.txt'
